USE [AX20160530]
GO

/****** Object:  Table [dbo].[XT_TPRESTIGEMANAGEBYCONTRACT]    Script Date: 2016/6/20 10:58:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[XT_TPRESTIGEMANAGEBYCONTRACT](
	[CUSTACCOUNT] [nvarchar](20) NOT NULL DEFAULT (''),
	[CUSTNAME] [nvarchar](60) NOT NULL DEFAULT (''),
	[CASHBALANCE] [numeric](28, 12) NOT NULL DEFAULT ((0)),
	[BILLBALANCETHREEMONTHS] [numeric](28, 12) NOT NULL DEFAULT ((0)),
	[BILLBALANCESIXMONTHS] [numeric](28, 12) NOT NULL DEFAULT ((0)),
	[PRESTIGEQUOTA] [numeric](28, 12) NOT NULL DEFAULT ((0)),
	[TEMPORARYBALANCE] [numeric](28, 12) NOT NULL DEFAULT ((0)),
	[TEMPORARYAMOUNT] [numeric](28, 12) NOT NULL DEFAULT ((0)),
	[WARNINGAMOUNT] [numeric](28, 12) NOT NULL DEFAULT ((0)),
	[TEMPORARYTAKEEFFECT] [int] NOT NULL DEFAULT ((0)),
	[FAILUREDATE] [datetime] NOT NULL DEFAULT ('1900-01-01 00:00:00.000'),
	[XTETEMPCREDITNUM] [nvarchar](20) NOT NULL DEFAULT (''),
	[CMT_CONTRACTID] [nvarchar](50) NOT NULL DEFAULT (''),
	[DATAAREAID] [nvarchar](3) NOT NULL DEFAULT ('dat'),
	[RECVERSION] [int] NOT NULL DEFAULT ((1)),
	[RECID] [bigint] NOT NULL,
 CONSTRAINT [I_50556CUSTACCOUNT] PRIMARY KEY NONCLUSTERED 
(
	[DATAAREAID] ASC,
	[CMT_CONTRACTID] ASC,
	[CUSTACCOUNT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[XT_TPRESTIGEMANAGEBYCONTRACT]  WITH CHECK ADD CHECK  (([RECID]<>(0)))
GO

