USE [AX20160530]
GO

/****** Object:  Table [dbo].[XT_CUSTPRESTIGEQUOTALOG]    Script Date: 2016/6/20 11:44:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[XT_CUSTPRESTIGEQUOTALOG](
	[XTSUBCASH] [numeric](28, 12) NOT NULL DEFAULT ((0)),
	[XTSUBSIXBILL] [numeric](28, 12) NOT NULL DEFAULT ((0)),
	[XTSUBTHREEBILL] [numeric](28, 12) NOT NULL DEFAULT ((0)),
	[XTSUBTMP] [numeric](28, 12) NOT NULL DEFAULT ((0)),
	[CUSTACCOUNT] [nvarchar](20) NOT NULL DEFAULT (''),
	[PACKINGSLIPID] [nvarchar](20) NOT NULL DEFAULT (''),
	[CPSREFRECID] [bigint] NOT NULL DEFAULT ((0)),
	[REMARK] [nvarchar](250) NOT NULL DEFAULT (''),
	[CREATEDDATE] [datetime] NOT NULL DEFAULT ('1900-01-01 00:00:00.000'),
	[CREATEDTIME] [int] NOT NULL DEFAULT ((0)),
	[CREATEDBY] [nvarchar](5) NOT NULL DEFAULT ('?'),
	[DATAAREAID] [nvarchar](3) NOT NULL DEFAULT ('dat'),
	[RECVERSION] [int] NOT NULL DEFAULT ((1)),
	[RECID] [bigint] NOT NULL
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[XT_CUSTPRESTIGEQUOTALOG]  WITH CHECK ADD CHECK  (([RECID]<>(0)))
GO

