USE [AX20160530]
GO

/****** Object:  Table [dbo].[XTTINVENTCENTERTABLE]    Script Date: 2016/6/20 11:04:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[XTTINVENTCENTERTABLE](
	[INVENTCENTERID] [nvarchar](20) NOT NULL DEFAULT (''),
	[NAME] [nvarchar](60) NOT NULL DEFAULT (''),
	[DATAAREAID] [nvarchar](3) NOT NULL DEFAULT ('dat'),
	[RECVERSION] [int] NOT NULL DEFAULT ((1)),
	[RECID] [bigint] NOT NULL,
	[PRODCAPACITY] [nvarchar](20) NOT NULL DEFAULT (''),
	[INVENTCENTERTYPE] [int] NOT NULL DEFAULT ((0)),
	[XTCOEFFICIENT] [numeric](28, 12) NOT NULL DEFAULT ((0)),
	[XTFENMOCENTERID] [nvarchar](20) NOT NULL DEFAULT (''),
	[PRODBUSINESSTYPE] [int] NOT NULL DEFAULT ((0)),
	[PRODLINEID] [nvarchar](20) NOT NULL DEFAULT (''),
 CONSTRAINT [I_50926INVENTCENTERIDX] PRIMARY KEY CLUSTERED 
(
	[DATAAREAID] ASC,
	[INVENTCENTERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[XTTINVENTCENTERTABLE]  WITH CHECK ADD CHECK  (([RECID]<>(0)))
GO

