USE [AX20160530]
GO

/****** Object:  Table [dbo].[INVENTDIM]    Script Date: 2016/6/20 10:54:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[INVENTDIM](
	[INVENTDIMID] [nvarchar](20) NOT NULL DEFAULT (''),
	[INVENTBATCHID] [nvarchar](20) NOT NULL DEFAULT (''),
	[WMSLOCATIONID] [nvarchar](10) NOT NULL DEFAULT (''),
	[INVENTSERIALID] [nvarchar](20) NOT NULL DEFAULT (''),
	[INVENTLOCATIONID] [nvarchar](20) NOT NULL DEFAULT (''),
	[DATAAREAID] [nvarchar](3) NOT NULL DEFAULT ('dat'),
	[RECVERSION] [int] NOT NULL DEFAULT ((1)),
	[RECID] [bigint] NOT NULL,
	[XTINVENTCENTERID] [nvarchar](20) NOT NULL DEFAULT (''),
 CONSTRAINT [I_698DIMIDIDX] PRIMARY KEY CLUSTERED 
(
	[DATAAREAID] ASC,
	[INVENTDIMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[INVENTDIM]  WITH CHECK ADD CHECK  (([RECID]<>(0)))
GO

