USE [AX20160530]
GO

/****** Object:  Table [dbo].[XT_TCOMPACTADDTREATYTRANS]    Script Date: 2016/6/20 11:42:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[XT_TCOMPACTADDTREATYTRANS](
	[XTEADJUSTBILLNUM] [nvarchar](20) NOT NULL DEFAULT (''),
	[CMT_CONTRACTID] [nvarchar](50) NOT NULL DEFAULT (''),
	[CUSTACCOUNT] [nvarchar](20) NOT NULL DEFAULT (''),
	[ITEMID] [nvarchar](20) NOT NULL DEFAULT (''),
	[ADJUSTPRICE] [numeric](28, 12) NOT NULL DEFAULT ((0)),
	[SELECTS] [int] NOT NULL DEFAULT ((0)),
	[PRICE] [numeric](28, 12) NOT NULL DEFAULT ((0)),
	[XSQYBM] [nvarchar](10) NOT NULL DEFAULT (''),
	[XTREFSALESID] [bigint] NOT NULL DEFAULT ((0)),
	[SALESQTY] [numeric](28, 12) NOT NULL DEFAULT ((0)),
	[CMT_PACKTYPE] [int] NOT NULL DEFAULT ((0)),
	[TAKEEFFECTDATE] [datetime] NOT NULL DEFAULT ('1900-01-01 00:00:00.000'),
	[TAKEEFFECTTIME] [int] NOT NULL DEFAULT ((0)),
	[ISVERIFY] [int] NOT NULL DEFAULT ((0)),
	[OLDXTEADJUSTBILLNUM] [nvarchar](20) NOT NULL DEFAULT (''),
	[DATAAREAID] [nvarchar](3) NOT NULL DEFAULT ('dat'),
	[RECVERSION] [int] NOT NULL DEFAULT ((1)),
	[RECID] [bigint] NOT NULL
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[XT_TCOMPACTADDTREATYTRANS]  WITH CHECK ADD CHECK  (([RECID]<>(0)))
GO

