unit MyLibrary_Intf;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ Do not modify this unit manually, or your changes will be lost when this   }
{ unit is regenerated the next time you compile the project.                 }
{----------------------------------------------------------------------------}

{$I RemObjects.inc}

interface

uses
  {vcl:} Classes, TypInfo,
  {RemObjects:} uROXMLIntf, uROClasses, uROClient, uROTypes, uROClientIntf;

const
  { Library ID }
  LibraryUID = '{C9714D0F-BE9C-4E22-AD7A-AFEC3EA58BDC}';
  TargetNamespace = '';

  { Service Interface ID's }
  IRemService_IID : TGUID = '{6E787EC4-8E42-4530-AD4A-06726D310F3E}';

  { Event ID's }

type
  { Forward declarations }
  IRemService = interface;


  { IRemService }
  IRemService = interface
    ['{6E787EC4-8E42-4530-AD4A-06726D310F3E}']
    function GetServerTime: DateTime;
    function DL2WRZSINFO(const BusinessType: Widestring; const XMLPrimaryKey: Variant): Integer;
  end;

  { CoRemService }
  CoRemService = class
    class function Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IRemService;
  end;

  { TRemService_Proxy }
  TRemService_Proxy = class(TROProxy, IRemService)
  protected
    function __GetInterfaceName:string; override;

    function GetServerTime: DateTime;
    function DL2WRZSINFO(const BusinessType: Widestring; const XMLPrimaryKey: Variant): Integer;
  end;

implementation

uses
  {vcl:} SysUtils,
  {RemObjects:} uROEventRepository, uROSerializer, uRORes;

{ CoRemService }

class function CoRemService.Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IRemService;
begin
  result := TRemService_Proxy.Create(aMessage, aTransportChannel);
end;

{ TRemService_Proxy }

function TRemService_Proxy.__GetInterfaceName:string;
begin
  result := 'RemService';
end;

function TRemService_Proxy.GetServerTime: DateTime;
begin
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'MyLibrary', __InterfaceName, 'GetServerTime');
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('Result', TypeInfo(DateTime), result, [paIsDateTime]);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

function TRemService_Proxy.DL2WRZSINFO(const BusinessType: Widestring; const XMLPrimaryKey: Variant): Integer;
begin
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'MyLibrary', __InterfaceName, 'DL2WRZSINFO');
    __Message.Write('BusinessType', TypeInfo(Widestring), BusinessType, []);
    __Message.Write('XMLPrimaryKey', TypeInfo(Variant), XMLPrimaryKey, []);
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('Result', TypeInfo(Integer), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

initialization
  RegisterProxyClass(IRemService_IID, TRemService_Proxy);


finalization
  UnregisterProxyClass(IRemService_IID);

end.
