
GO

/****** Object:  Table [dbo].[XT_ERPTOWRZSSENDDATAINFO]    Script Date: 09/25/2017 16:10:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[XT_ERPTOWRZSSENDDATAINFO](
	[COMPANYID] [nvarchar](4) NOT NULL,
	[PROCESSFLAG] [int] NOT NULL,
	[XTINDEXXML] [nvarchar](1000) NOT NULL,
	[XTPROCESSID] [nvarchar](20) NOT NULL,
	[CREATEDDATETIME] [datetime] NOT NULL,
	[CREATEDBY] [nvarchar](8) NOT NULL,
	[RECVERSION] [int] NOT NULL,
	[PARTITION] [bigint] NOT NULL,
	[RECID] [bigint] NOT NULL,
	[OPERATION] [nvarchar](10) NOT NULL,
	[REFRECID] [bigint] NOT NULL,
	[RESULT] [nvarchar](10) NOT NULL,
	[SENDNUM] [int] NOT NULL,
	[SyncStart] [datetime] NULL,
	[SyncDone] [datetime] NULL,
	[SyncCounter] [int] NOT NULL
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[XT_ERPTOWRZSSENDDATAINFO]  WITH CHECK ADD CHECK  (([RECID]<>(0)))
GO

ALTER TABLE [dbo].[XT_ERPTOWRZSSENDDATAINFO] ADD  DEFAULT ('') FOR [COMPANYID]
GO

ALTER TABLE [dbo].[XT_ERPTOWRZSSENDDATAINFO] ADD  DEFAULT ((0)) FOR [PROCESSFLAG]
GO

ALTER TABLE [dbo].[XT_ERPTOWRZSSENDDATAINFO] ADD  DEFAULT ('') FOR [XTINDEXXML]
GO

ALTER TABLE [dbo].[XT_ERPTOWRZSSENDDATAINFO] ADD  DEFAULT ('') FOR [XTPROCESSID]
GO

ALTER TABLE [dbo].[XT_ERPTOWRZSSENDDATAINFO] ADD  DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) FOR [CREATEDDATETIME]
GO

ALTER TABLE [dbo].[XT_ERPTOWRZSSENDDATAINFO] ADD  DEFAULT ('?') FOR [CREATEDBY]
GO

ALTER TABLE [dbo].[XT_ERPTOWRZSSENDDATAINFO] ADD  DEFAULT ((1)) FOR [RECVERSION]
GO

ALTER TABLE [dbo].[XT_ERPTOWRZSSENDDATAINFO] ADD  DEFAULT ((5637144576.)) FOR [PARTITION]
GO

ALTER TABLE [dbo].[XT_ERPTOWRZSSENDDATAINFO] ADD  DEFAULT ('') FOR [OPERATION]
GO

ALTER TABLE [dbo].[XT_ERPTOWRZSSENDDATAINFO] ADD  DEFAULT ((0)) FOR [REFRECID]
GO

ALTER TABLE [dbo].[XT_ERPTOWRZSSENDDATAINFO] ADD  DEFAULT ('') FOR [RESULT]
GO

ALTER TABLE [dbo].[XT_ERPTOWRZSSENDDATAINFO] ADD  DEFAULT ((0)) FOR [SENDNUM]
GO

ALTER TABLE [dbo].[XT_ERPTOWRZSSENDDATAINFO] ADD  DEFAULT ((0)) FOR [SyncCounter]
GO


